### PR TITLE
Upgrade to 0.6.1

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
I can train a model but I get a nasty test failure.  Any ideas @matt-gardner ?

```
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.6, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: /Users/michael/hack/allenai/allennlp-as-a-library-example, inifile: pytest.ini
plugins: flaky-3.4.0
collected 3 items                                                                                                                                            

tests/dataset_readers/semantic_scholar_dataset_reader_test.py .                                                                                        [ 33%]
tests/models/academic_paper_classifier_test.py .                                                                                                       [ 66%]
tests/predictors/predictor_test.py F                                                                                                                   [100%]

========================================================================== FAILURES ==========================================================================
____________________________________________________ TestPaperClassifierPredictor.test_uses_named_inputs _____________________________________________________

self = <predictor_test.TestPaperClassifierPredictor testMethod=test_uses_named_inputs>

    def test_uses_named_inputs(self):
        inputs = {
            "title": "Interferring Discourse Relations in Context",
            "paperAbstract": (
                    "We investigate various contextual effects on text "
                    "interpretation, and account for them by providing "
                    "contextual constraints in a logical theory of text "
                    "interpretation. On the basis of the way these constraints "
                    "interact with the other knowledge sources, we draw some "
                    "general conclusions about the role of domain-specific "
                    "information, top-down and bottom-up discourse information "
                    "flow, and the usefulness of formalisation in discourse theory."
            )
        }
    
        archive = load_archive('tests/fixtures/model.tar.gz')
        predictor = Predictor.from_archive(archive, 'paper-classifier')
    
>       result = predictor.predict_json(inputs)

tests/predictors/predictor_test.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/predictors/predictor.py:50: in predict_json
    return self.predict_instance(instance)
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/predictors/predictor.py:53: in predict_instance
    outputs = self._model.forward_on_instance(instance)
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/models/model.py:124: in forward_on_instance
    return self.forward_on_instances([instance])[0]
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/models/model.py:152: in forward_on_instances
    dataset = Batch(instances)
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/data/dataset.py:33: in __init__
    self._check_types()
../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/data/dataset.py:41: in _check_types
    for x in self.instances]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x121b96e48>

    all_instance_fields_and_types: List[Dict[str, str]] = [{k: v.__class__.__name__
                                                            for k, v in x.fields.items()}
>                                                          for x in self.instances]
E   AttributeError: 'tuple' object has no attribute 'fields'

../../../miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/data/dataset.py:41: AttributeError
===Flaky Test Report===


===End Flaky Test Report===
====================================================================== warnings summary ======================================================================
/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/service/predictors/__init__.py:23: FutureWarning: allennlp.service.predictors.* has been depreciated. Please use allennlp.predictors.*
  "Please use allennlp.predictors.*", FutureWarning)

/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/service/predictors/predictor.py:6: FutureWarning: allennlp.service.predictors.* has been deprecated. Please use allennlp.predictors.*
  " Please use allennlp.predictors.*", FutureWarning)

/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py:122: DeprecationWarning: the token embedders for BasicTextFieldEmbedder should now be specified as a dict under the 'token_embedders' key, not as top-level key-value pairs
  warnings.warn(DeprecationWarning("the token embedders for BasicTextFieldEmbedder should now "
/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py:122: DeprecationWarning: the token embedders for BasicTextFieldEmbedder should now be specified as a dict under the 'token_embedders' key, not as top-level key-value pairs
  warnings.warn(DeprecationWarning("the token embedders for BasicTextFieldEmbedder should now "
/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py:122: DeprecationWarning: the token embedders for BasicTextFieldEmbedder should now be specified as a dict under the 'token_embedders' key, not as top-level key-value pairs
  warnings.warn(DeprecationWarning("the token embedders for BasicTextFieldEmbedder should now "

/Users/michael/miniconda3/envs/allennlp-tut/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py:122: DeprecationWarning: the token embedders for BasicTextFieldEmbedder should now be specified as a dict under the 'token_embedders' key, not as top-level key-value pairs
  warnings.warn(DeprecationWarning("the token embedders for BasicTextFieldEmbedder should now "

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================= 1 failed, 2 passed, 6 warnings in 3.56 seconds =======================================================
```

**Comment by matt-gardner** [comment]
Thanks for doing this, it's been on my list for a while.  Maybe try adding the fix from #10?

**Comment by schmmd** [comment]
@matt-gardner thanks for the pointer--I didn't realize how many PRs there were ;-P

That didn't do it, but I have an idea.

**Comment by schmmd** [comment]
@matt-gardner tests pass now.

**Review by matt-gardner — APPROVED** [review]

**Pull request merged**
