### PR TITLE
Fix interaction between demo and predictor

### PR DESCRIPTION
**Pull request by seal6363**
Fixed https://github.com/allenai/allennlp/issues/1988

### CODE REVIEW

**Review by schmmd — APPROVED** [review]
Woohoo!  Do you have a PR on the allennlp-as-a-library repo too?

**Comment by nelson-liu** [comment]
@schmmd did you want to merge this?

**Comment by nelson-liu** [comment]
also do we need to bump the allennlp pin if we merge this?

**Comment by nelson-liu** [comment]
(before we merge this, i want to trigger CI on it)

**Review by matt-gardner — APPROVED** [review]
LGTM!

**Comment by schmmd** [comment]
@nelson-liu thanks for taking care of this.  Sorry for the slow responses but I was on PTO.  Great to have this fixed @seal6363 !

**Pull request merged**
